name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-escript:
    name: Build escripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: "1.20.2-otp-29"
            otp_release: "29.0.3"
    steps:
    - uses: actions/checkout@v7
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp_release }}
    - name: Install dependencies
      run: mix deps.get
    - name: Test
      run: mix test
    - name: Build escript
      run: mix escript.build
    - name: Rename escript
      run: "mv smppsend smppsend-escript-${{ matrix.otp_release }}"
    - uses: actions/upload-artifact@v7
      with:
        name: otp-${{ matrix.otp_release }}
        path: smppsend-escript-${{ matrix.otp_release }}

  build-burrito:
    name: Build Burrito executables
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v7
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.20.2-otp-29"
          otp-version: "29.0.3"

      - uses: goto-bus-stop/setup-zig@v2.2.1
        with:
          version: 0.15.2
      - name: Build Burrito
        run: |
          mix deps.get
          mix compile
          mix release smppsend --overwrite
      - uses: actions/upload-artifact@v7
        with:
          name: burrito-images
          path: burrito_out/*

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs:
      - build-escript
      - build-burrito
    steps:
    - uses: actions/checkout@v7
    - name: Download artifacts
      uses: actions/download-artifact@v8
    - name: Create GitHub release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if gh release view "$GITHUB_REF_NAME" >/dev/null 2>&1; then
          gh release upload "$GITHUB_REF_NAME" otp-*/smppsend-* burrito-images/* --clobber
        else
          gh release create "$GITHUB_REF_NAME" otp-*/smppsend-* burrito-images/* \
            --title "Precompiled smppsend for the latest OTP versions" \
            --notes "Release $GITHUB_REF_NAME" \
            --verify-tag
        fi
